/* Auto-generated by genmsg_cpp for file /home/karthik/karthik_sandbox/github_repos/folding/folding_srvs/srv/ExecuteFold.srv */
#ifndef FOLDING_SRVS_SERVICE_EXECUTEFOLD_H
#define FOLDING_SRVS_SERVICE_EXECUTEFOLD_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "ros/service_traits.h"

#include "folding_msgs/FoldTraj.h"



namespace folding_srvs
{
template <class ContainerAllocator>
struct ExecuteFoldRequest_ : public ros::Message
{
  typedef ExecuteFoldRequest_<ContainerAllocator> Type;

  ExecuteFoldRequest_()
  : fold_traj()
  {
  }

  ExecuteFoldRequest_(const ContainerAllocator& _alloc)
  : fold_traj(_alloc)
  {
  }

  typedef  ::folding_msgs::FoldTraj_<ContainerAllocator>  _fold_traj_type;
   ::folding_msgs::FoldTraj_<ContainerAllocator>  fold_traj;


private:
  static const char* __s_getDataType_() { return "folding_srvs/ExecuteFoldRequest"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "c35cb545a0cdcce64a14e6890fd63118"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "3e78e4eec8da5701d6f887e332038580"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "folding_msgs/FoldTraj fold_traj\n\
\n\
================================================================================\n\
MSG: folding_msgs/FoldTraj\n\
geometry_msgs/PointStamped[] approach_points\n\
geometry_msgs/PointStamped[] grip_points\n\
geometry_msgs/PointStamped[] quarter_points\n\
geometry_msgs/PointStamped[] weight_points\n\
geometry_msgs/PointStamped[] vertical_points\n\
geometry_msgs/PointStamped[] goal_points\n\
geometry_msgs/PointStamped smooth_center\n\
geometry_msgs/PointStamped[] smooth_edges\n\
bool ignore_smooth\n\
float64[] tilts\n\
bool red\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PointStamped\n\
# This represents a Point with reference coordinate frame and timestamp\n\
Header header\n\
Point point\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, fold_traj);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, fold_traj);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(fold_traj);
    return size;
  }

  typedef boost::shared_ptr< ::folding_srvs::ExecuteFoldRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::folding_srvs::ExecuteFoldRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct ExecuteFoldRequest
typedef  ::folding_srvs::ExecuteFoldRequest_<std::allocator<void> > ExecuteFoldRequest;

typedef boost::shared_ptr< ::folding_srvs::ExecuteFoldRequest> ExecuteFoldRequestPtr;
typedef boost::shared_ptr< ::folding_srvs::ExecuteFoldRequest const> ExecuteFoldRequestConstPtr;


template <class ContainerAllocator>
struct ExecuteFoldResponse_ : public ros::Message
{
  typedef ExecuteFoldResponse_<ContainerAllocator> Type;

  ExecuteFoldResponse_()
  : success(false)
  {
  }

  ExecuteFoldResponse_(const ContainerAllocator& _alloc)
  : success(false)
  {
  }

  typedef uint8_t _success_type;
  uint8_t success;


private:
  static const char* __s_getDataType_() { return "folding_srvs/ExecuteFoldResponse"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "358e233cde0c8a8bcfea4ce193f8fc15"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "3e78e4eec8da5701d6f887e332038580"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "bool success\n\
\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, success);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, success);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(success);
    return size;
  }

  typedef boost::shared_ptr< ::folding_srvs::ExecuteFoldResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::folding_srvs::ExecuteFoldResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct ExecuteFoldResponse
typedef  ::folding_srvs::ExecuteFoldResponse_<std::allocator<void> > ExecuteFoldResponse;

typedef boost::shared_ptr< ::folding_srvs::ExecuteFoldResponse> ExecuteFoldResponsePtr;
typedef boost::shared_ptr< ::folding_srvs::ExecuteFoldResponse const> ExecuteFoldResponseConstPtr;

struct ExecuteFold
{

typedef ExecuteFoldRequest Request;
typedef ExecuteFoldResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct ExecuteFold
} // namespace folding_srvs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::folding_srvs::ExecuteFoldRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "c35cb545a0cdcce64a14e6890fd63118";
  }

  static const char* value(const  ::folding_srvs::ExecuteFoldRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xc35cb545a0cdcce6ULL;
  static const uint64_t static_value2 = 0x4a14e6890fd63118ULL;
};

template<class ContainerAllocator>
struct DataType< ::folding_srvs::ExecuteFoldRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "folding_srvs/ExecuteFoldRequest";
  }

  static const char* value(const  ::folding_srvs::ExecuteFoldRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::folding_srvs::ExecuteFoldRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "folding_msgs/FoldTraj fold_traj\n\
\n\
================================================================================\n\
MSG: folding_msgs/FoldTraj\n\
geometry_msgs/PointStamped[] approach_points\n\
geometry_msgs/PointStamped[] grip_points\n\
geometry_msgs/PointStamped[] quarter_points\n\
geometry_msgs/PointStamped[] weight_points\n\
geometry_msgs/PointStamped[] vertical_points\n\
geometry_msgs/PointStamped[] goal_points\n\
geometry_msgs/PointStamped smooth_center\n\
geometry_msgs/PointStamped[] smooth_edges\n\
bool ignore_smooth\n\
float64[] tilts\n\
bool red\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PointStamped\n\
# This represents a Point with reference coordinate frame and timestamp\n\
Header header\n\
Point point\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
";
  }

  static const char* value(const  ::folding_srvs::ExecuteFoldRequest_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::folding_srvs::ExecuteFoldResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const  ::folding_srvs::ExecuteFoldResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::folding_srvs::ExecuteFoldResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "folding_srvs/ExecuteFoldResponse";
  }

  static const char* value(const  ::folding_srvs::ExecuteFoldResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::folding_srvs::ExecuteFoldResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool success\n\
\n\
\n\
";
  }

  static const char* value(const  ::folding_srvs::ExecuteFoldResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::folding_srvs::ExecuteFoldResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::folding_srvs::ExecuteFoldRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.fold_traj);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ExecuteFoldRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::folding_srvs::ExecuteFoldResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.success);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ExecuteFoldResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<folding_srvs::ExecuteFold> {
  static const char* value() 
  {
    return "3e78e4eec8da5701d6f887e332038580";
  }

  static const char* value(const folding_srvs::ExecuteFold&) { return value(); } 
};

template<>
struct DataType<folding_srvs::ExecuteFold> {
  static const char* value() 
  {
    return "folding_srvs/ExecuteFold";
  }

  static const char* value(const folding_srvs::ExecuteFold&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<folding_srvs::ExecuteFoldRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "3e78e4eec8da5701d6f887e332038580";
  }

  static const char* value(const folding_srvs::ExecuteFoldRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<folding_srvs::ExecuteFoldRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "folding_srvs/ExecuteFold";
  }

  static const char* value(const folding_srvs::ExecuteFoldRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<folding_srvs::ExecuteFoldResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "3e78e4eec8da5701d6f887e332038580";
  }

  static const char* value(const folding_srvs::ExecuteFoldResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<folding_srvs::ExecuteFoldResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "folding_srvs/ExecuteFold";
  }

  static const char* value(const folding_srvs::ExecuteFoldResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // FOLDING_SRVS_SERVICE_EXECUTEFOLD_H

