/* Auto-generated by genmsg_cpp for file /home/karthik/karthik_sandbox/github_repos/folding/folding_msgs/msg/GripsTarget.msg */
#ifndef FOLDING_MSGS_MESSAGE_GRIPSTARGET_H
#define FOLDING_MSGS_MESSAGE_GRIPSTARGET_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "folding_msgs/GripTarget.h"
#include "folding_msgs/GripTarget.h"

namespace folding_msgs
{
template <class ContainerAllocator>
struct GripsTarget_ : public ros::Message
{
  typedef GripsTarget_<ContainerAllocator> Type;

  GripsTarget_()
  : l_target()
  , r_target()
  {
  }

  GripsTarget_(const ContainerAllocator& _alloc)
  : l_target(_alloc)
  , r_target(_alloc)
  {
  }

  typedef  ::folding_msgs::GripTarget_<ContainerAllocator>  _l_target_type;
   ::folding_msgs::GripTarget_<ContainerAllocator>  l_target;

  typedef  ::folding_msgs::GripTarget_<ContainerAllocator>  _r_target_type;
   ::folding_msgs::GripTarget_<ContainerAllocator>  r_target;


private:
  static const char* __s_getDataType_() { return "folding_msgs/GripsTarget"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "05ff55cecb9155554097e097eaf570d9"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "GripTarget l_target\n\
GripTarget r_target\n\
\n\
================================================================================\n\
MSG: folding_msgs/GripTarget\n\
geometry_msgs/PointStamped point\n\
string arm\n\
bool grip\n\
float64 pitch\n\
float64 roll\n\
float64 yaw\n\
bool empty\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PointStamped\n\
# This represents a Point with reference coordinate frame and timestamp\n\
Header header\n\
Point point\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, l_target);
    ros::serialization::serialize(stream, r_target);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, l_target);
    ros::serialization::deserialize(stream, r_target);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(l_target);
    size += ros::serialization::serializationLength(r_target);
    return size;
  }

  typedef boost::shared_ptr< ::folding_msgs::GripsTarget_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::folding_msgs::GripsTarget_<ContainerAllocator>  const> ConstPtr;
}; // struct GripsTarget
typedef  ::folding_msgs::GripsTarget_<std::allocator<void> > GripsTarget;

typedef boost::shared_ptr< ::folding_msgs::GripsTarget> GripsTargetPtr;
typedef boost::shared_ptr< ::folding_msgs::GripsTarget const> GripsTargetConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::folding_msgs::GripsTarget_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::folding_msgs::GripsTarget_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace folding_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::folding_msgs::GripsTarget_<ContainerAllocator> > {
  static const char* value() 
  {
    return "05ff55cecb9155554097e097eaf570d9";
  }

  static const char* value(const  ::folding_msgs::GripsTarget_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x05ff55cecb915555ULL;
  static const uint64_t static_value2 = 0x4097e097eaf570d9ULL;
};

template<class ContainerAllocator>
struct DataType< ::folding_msgs::GripsTarget_<ContainerAllocator> > {
  static const char* value() 
  {
    return "folding_msgs/GripsTarget";
  }

  static const char* value(const  ::folding_msgs::GripsTarget_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::folding_msgs::GripsTarget_<ContainerAllocator> > {
  static const char* value() 
  {
    return "GripTarget l_target\n\
GripTarget r_target\n\
\n\
================================================================================\n\
MSG: folding_msgs/GripTarget\n\
geometry_msgs/PointStamped point\n\
string arm\n\
bool grip\n\
float64 pitch\n\
float64 roll\n\
float64 yaw\n\
bool empty\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PointStamped\n\
# This represents a Point with reference coordinate frame and timestamp\n\
Header header\n\
Point point\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
";
  }

  static const char* value(const  ::folding_msgs::GripsTarget_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::folding_msgs::GripsTarget_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.l_target);
    stream.next(m.r_target);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GripsTarget_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::folding_msgs::GripsTarget_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::folding_msgs::GripsTarget_<ContainerAllocator> & v) 
  {
    s << indent << "l_target: ";
s << std::endl;
    Printer< ::folding_msgs::GripTarget_<ContainerAllocator> >::stream(s, indent + "  ", v.l_target);
    s << indent << "r_target: ";
s << std::endl;
    Printer< ::folding_msgs::GripTarget_<ContainerAllocator> >::stream(s, indent + "  ", v.r_target);
  }
};


} // namespace message_operations
} // namespace ros

#endif // FOLDING_MSGS_MESSAGE_GRIPSTARGET_H

